apiVersion: v1
kind: ConfigMap
metadata:
  name: service-b-cm
  namespace: dev
data:
  SERVER_PORT: '8080'
  SPRING_PROFILES_ACTIVE: dev
  TZ: 'Europe/Madrid'
  TRACES_ENDPOINT: 'http://jaeger-collector.istio-system.svc.cluster.local:9411'
  SERVICE_C_HELLO_URL: 'http://gateway-svc/service-c/hello/direct'
  SERVICE_C_USER_URL: 'http://gateway-svc/service-c/user/'
  SERVICE_C_USERS_URL: 'http://gateway-svc/service-c/user/users'
  SERVICE_PYTHON_1_URL: 'http://gateway-svc/service-python-1/'
  